### ISSUE TITLE
Subgraph Isomorphism

### ISSUE THREAD

**Issue by yolapop** [fozziethebeat/S-Space#62]
Hi, is there anyway to calculate subgraph isomorphism?
I've searched along the source code but there's only `VF2State` which is for graph isomorphism, not subgraph isomorphism.

Thank you.

**Comment by davidjurgens** [comment]
Hi Yolanda,

  What do you mean by subgraph isomorphism?  Are you testing for whether
there exist subgraphs of two graphs that are isomorphic?

  Thanks,
  David

**Comment by yolapop** [comment]
By subgraph isomorphism I mean searching for occurence(s) of smaller graph (A) in the larger graph (B).

In the original `vflib2`, there are files `vf2_sub_state.h` and `vf2_sub_state.cc` and I've been trying to port that myself by looking at your library and those two files but I'm afraid there's some error because it took a long running time.

Another example is from [boost graph library](http://www.boost.org/doc/libs/1_57_0/libs/graph/doc/vf2_sub_graph_iso.html). In this library, it searches for all occurences of smaller graph A in larger graph B but I only want to search one occurence.

**Comment by yolapop** [comment]
Hi @davidjurgens,

I've done some testing between the original VFLib2 and Boost Graph. I found that VFLib2 is very slow compared to Boost Graph. Can you confirm this? I used small graph with 10 nodes and large graph with ~550 nodes. That's why when I tried S-Space, my code was running for days to search for subgraph iso.

If you need my source file, I'll gladly send it to you.

Thank you.

**Comment by davidjurgens** [comment]
Hi Yolanda,

  I haven't used Boost Graph much so unfortunately, I can't really comment
on the speed difference.  We originally went with VFLib2 because it was the
fastest at the time and was relatively straight-forward to port to Java.

  Per your earlier question, we haven't really looked into subgraph
matching like you describe.  The current code was used for network motif
detection but for relatively small motifs, so we never needed to port the
full VF2 library code.

  Thanks,
  David

On Mon, Apr 13, 2015 at 12:16 AM, Yolanda Septiana <notifications@github.com

**Comment by yolapop** [comment]
Thanks for your reply.

Apparently I should use *time hog* approach which will terminate searches that are running above 100ms.
